### ISSUE TITLE
IssueOrder

### ISSUE THREAD

**Issue by llxiaoyuan** [matkhl/leagueoflegends#12]
this rep is very useful，thanks sir，but i am very curious at “how to find IssueOrder check”

#define oObjIssueOrderFloatCheck1 0x84
#define oObjIssueOrderFloatCheck2 0x88
#define oObjIssueOrderCheck 0xD4

i just find 0xD4，maybe this is oObjIssueOrderCheck 
![image](https://github.com/matkhl/leagueoflegends/assets/36320938/7b9a199a-a5ff-4411-a2b2-21d9635102d0)

**Comment by jinxx0** [comment]
Did u fixed crash when injecting dll?

**Comment by llxiaoyuan** [comment]
i just use some code of this repo，so i don't need to fix crash

**Comment by matkhl** [comment]
> this rep is very useful，thanks sir，but i am very curious at “how to find IssueOrder check”
> 
> 
> 
> #define oObjIssueOrderFloatCheck1 0x84
> 
> #define oObjIssueOrderFloatCheck2 0x88
> 
> #define oObjIssueOrderCheck 0xD4
> 
> 
> 
> i just find 0xD4，maybe this is oObjIssueOrderCheck 
> 
> ![image](https://github.com/matkhl/leagueoflegends/assets/36320938/7b9a199a-a5ff-4411-a2b2-21d9635102d0)

Th one you found seems to be correct. The Value has to be zero in order for Issue order to get called and its tested inside an if clause. Thats why i called it IssueOrderCheck. Good work :)

**Comment by llxiaoyuan** [comment]
and IssueMove didn't make player move sometimes，i don‘t know why

**Comment by matkhl** [comment]
There is another check that sometimes doesnt allow issue move to get called. I remember i fixed it somehow.

**Comment by jinxx0** [comment]
> There is another check that sometimes doesnt allow issue move to get called. I remember i fixed it somehow.

Will u update offsets?
