### ISSUE TITLE
Import Handler (wow64) failed: 00000047

### ISSUE THREAD

**Issue by ReimuHakureii** [matkhl/leagueoflegends#7]
When opening start.exe. I have both of the injector files renamed that are required for it to work. Any thoughts on what might be causing this?

**Comment by matkhl** [comment]
This error appears when the "Injector SM.exe" file is missing.
Seems like i renamed it inside the GH Injector library source as well.
In that case it should work if you leave the default file name for that executable. "GH Injector SM - x64.exe"

**Comment by matkhl** [comment]
> I might have fixed it myself but now it says this in game but I can't open the menu Waiting for client to connect to pipe... Client connected. [2023-07-28 11:29:32] Injected [2023-07-28 11:29:32] Thread hidden Failed to read from named pipe, waiting for new connection... Waiting for client to connect to pipe... ![9cff7nhc](https://user-images.githubusercontent.com/63125235/256865564-25e63436-7597-4c0e-a221-9c0da21780f7.png)

Yes that means the dll is not injected.
The named pipe is just an external console independent from the chair.
It waits for the dll file to be injected.

**Comment by ReimuHakureii** [comment]
What I meant is that even after it successfully injects I can't open the GUI

**Comment by matkhl** [comment]
When the console sais "Waiting for client to connect to pipe...", that means it didnt inject yet.
Check the following:
You have these 3 files inside the output folder:
start.exe
Injector.dll (From GH library)
GH Injector SM - x64.exe (From GH library)

If it still doesnt work, execute the "start.exe" from the command line so you see the full output without it closing itself instantly.

**Comment by ReimuHakureii** [comment]
I recorded myself doing what u asked
[](https://streamable.com/bf2mux)

**Comment by matkhl** [comment]
Okay it seems like you need the "GH Injector SM - x86.exe" file.
I will update the README

**Comment by matkhl** [comment]
I updated the source. You shouldnt have to worry about renaming the files at all.

**Comment by ReimuHakureii** [comment]
yep it works now
