### ISSUE TITLE
Question about buffManager

### ISSUE THREAD

**Issue by vacnex** [matkhl/leagueoflegends#9]
Hi, thanks for making this great public source.
I'm building my own buffmanager management structure and i have referenced how you implemented and applied it in my project, and it works, and i want to change it a little bit according to my project structure and it doesn't seem to work exactly as I thought it would,
specifically I see you have implemented 2 functions GetBuffManagerEntriesEnd and GetBuffListSize in object class and I want to include these 2 functions in my Buffmanger as follows

```
BuffManager* Object::BuffHandle()
{
	return (BuffManager*)(*(uintptr_t*)((uintptr_t)this + Offsets::Buff::BuffManager));
}
class BuffManager
{
private:
	uintptr_t* GetBuffManagerEntriesEnd(){
		return (uintptr_t*)((uintptr_t)this + 0x10);
	};
	int GetBuffListSize()
	{
		return (int)(GetBuffManagerEntriesEnd() - (uintptr_t*)this) / (int)sizeof(uintptr_t);
	};
	BuffEntry* GetBuffEntryByIndex(int index)
	{
		BuffEntry* address = (BuffEntry*)(*(uintptr_t*)((uintptr_t)this + (sizeof(uintptr_t) * index)));
		if (!IsValidPtr(address)) return nullptr;
		return address;
	};
public:
	std::vector<Buff*> Buffs() {
		std::vector<Buff*> BuffArray;

		for (int i = 0; i < GetBuffListSize(); i++)
		{
			auto buffEntry = this->GetBuffEntryByIndex(i);
			if (!buffEntry) return BuffArray;
			auto buff = buffEntry->GetBuff();
			if (buff)
			{
				BuffArray.push_back(buff);
			}
		}
		return BuffArray;
	}
};
```
like i implemented above, when i debug and find out my GetBuffListSize() is always 0
I think it's because I did something wrong with the GetBuffListSize() function.

can you point out my mistake, thanks

**Comment by matkhl** [comment]
you cant access the "buffmanager entries end" pointer from inside the buffmanager. its an attribute of the gameobject that comes after the buffmanager pointer
